// <auto-generated />
namespace TP3_A1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AuteracoesFinais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuteracoesFinais));
        
        string IMigrationMetadata.Id
        {
            get { return "202411040044505_AuteracoesFinais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
